url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:rentdb}
username=${DB_USERNAME:rentuser}
password=${DB_PASSWORD:rentpass}
driver=org.postgresql.Driver
changeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml
contexts=dev
verbose=true